config/routes.rb
Rails.application.routes.draw do
  root 'beers#index'
  resources :beers
    
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def index
    @beers = Beer.all
  end

  def new
    @beer = Beer.new
  end

  def create
    Beer.create(beer_params)
    redirect_to root_path
  end

  private

  def beer_params
    params.require(:beer).permit(:name, :brewery, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/index.html.erb
<div class="hero"> 
    <br />
    <div class="frosty col-10 offset-1">
    <br />
        <h1>    beer</h1> 
        <h2>    /bir/</h2>   
        <h2><i>noun</i></h2>  
        <h3>    an alcoholic drink made from yeast-fermented malt flavored with hops</h3>
        <h4><i> "a pint of beer"</i></h4>

          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          
    </div>

<% @beers.each do |beer| %>
<div class="booyah-box col-10 offset-1">
  <h1><%= beer.name %></h1>
  <br>
  <br>
  <i><%= beer.brewery %></i><br /><br /> 
  <p><%= beer.description %></p><br />  
</div>

<hr />
<% end %>

app/views/beers/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>What are you drinking?</h1>

  <%= simple_form_for @beer do |f| %>
    <%= f.input :name %>
    <%= f.input :brewery %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Cheers!', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crafted</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Fredericka+the+Great&display=swap" rel="stylesheet">
    
  </head>

  <body>

  <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <%= link_to 'CRAFTED', root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          
          <%= link_to 'What are you drinking?', new_beer_path, class: 'nav-link' %>
        </li>        
      </ul>    
  </div>
</nav>

    <%= yield %>
  </body>
</html>